name: Build Linux

on: [push]

jobs:
  appimage-builder:
    name: Linux AppImage Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libgl1-mesa-dev libgtk-3-dev libxkbcommon-dev libunwind-dev libfuse2 -y

      - name: Install dependencies from BuildLinux.sh
        shell: bash
        run: sudo ./BuildLinux.sh -ur

      - name: Fix permissions
        shell: bash
        run: sudo chown $USER -R ./

      - name: Build deps
        working-directory: ${{ github.workspace }}
        run: ./BuildLinux.sh -dsr

      - name: Build Studio
        shell: bash
        run: ./BuildLinux.sh -ir
